### ISSUE TITLE
Kotlin script template class missing from classpath

### ISSUE THREAD

**Issue by aravance** [weirongxu/coc-kotlin#3]
### Result from CocInfo

> vim version: VIM - Vi IMproved 8.2 8022164
node version: v15.9.0
coc.nvim version: 0.0.80-6e5a2aaeb5
coc.nvim directory: /Users/me/.vim/plugged/coc.nvim
term: iTerm.app
platform: darwin

### Description

Open a kotlin script file e.g. `test.kts` and it shows an error missing script classes from the classpath.

`[kotlin MISSING_SCRIPT_STANDARD_TEMPLATE] [E] No script runtime was found in the classpath: class 'kotlin.script.templates.standard.ScriptTemplateWithArgs' not found. Please add kotlin-script-runtime.jar to`

### Extension version

0.0.5

**Comment by weirongxu** [comment]
https://github.com/fwcd/kotlin-language-server/issues/178
