### ISSUE TITLE
connect to server got closed

### ISSUE THREAD

**Issue by devilyouwei** [weirongxu/coc-kotlin#9]
Does the extension language server shut down?

**Comment by weirongxu** [comment]
Actually, I can't reproduce this. It could be an issue of Java version or Java environment, and there are some related issues on the official repository https://github.com/fwcd/vscode-kotlin/issues/83

**Comment by devilyouwei** [comment]
**Macbook air M1/MACOS Monterey/brew**

Ok, I just solved the issue "connect to server got closed", need to install java in the system first.
```bash
brew install openjdk
```
Then set java's bin environment in your bashrc or zshrc, whatever.

```
export BREW_HOME=/opt/homebrew
export PATH=$BREW_HOME/bin:$PATH
export PATH="$BREW_HOME/opt/openjdk/bin:$PATH"
```
